version: "3.8"

services:
  app:
    build: .
    image: server_v3:dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./:/app:delegated
    command: python app.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
